# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ricodigo-capistrano-recipes}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David A. Cuadrado"]
  s.date = %q{2011-05-25}
  s.default_executable = %q{ricodigo-install-server}
  s.description = %q{our capistrano recipes. forked from capistrano-recipes}
  s.email = %q{krawek@gmail.com}
  s.executables = ["ricodigo-install-server"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ricodigo-install-server",
    "generators/app.bluepill.erb",
    "generators/nginx.conf.erb",
    "generators/unicorn.rb.erb",
    "lib/helpers.rb",
    "lib/recipes/application.rb",
    "lib/recipes/assets.rb",
    "lib/recipes/bluepill.rb",
    "lib/recipes/bundler.rb",
    "lib/recipes/db.rb",
    "lib/recipes/deploy.rb",
    "lib/recipes/hooks.rb",
    "lib/recipes/log.rb",
    "lib/recipes/magent.rb",
    "lib/recipes/nginx.rb",
    "lib/recipes/symlinks.rb",
    "lib/recipes/unicorn.rb",
    "lib/ricodigo_capistrano_recipes.rb",
    "ricodigo-capistrano-recipes.gemspec"
  ]
  s.homepage = %q{http://github.com/ricodigo/ricodigo-capistrano-recipes}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{our capistrano recipes. forked from capistrano-recipes}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ssh>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano>, [">= 2.5.9"])
      s.add_runtime_dependency(%q<capistrano-ext>, [">= 1.2.1"])
      s.add_runtime_dependency(%q<mongoid>, [">= 0"])
      s.add_runtime_dependency(%q<unicorn>, [">= 0"])
      s.add_runtime_dependency(%q<magent>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<net-ssh>, [">= 0"])
      s.add_dependency(%q<capistrano>, [">= 2.5.9"])
      s.add_dependency(%q<capistrano-ext>, [">= 1.2.1"])
      s.add_dependency(%q<mongoid>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<magent>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-ssh>, [">= 0"])
    s.add_dependency(%q<capistrano>, [">= 2.5.9"])
    s.add_dependency(%q<capistrano-ext>, [">= 1.2.1"])
    s.add_dependency(%q<mongoid>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<magent>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

